spring:
  database:
    continue-on-error: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: limeEdu
    password: limeEdu1!
    url: jdbc:log4jdbc:mariadb://121.170.188.106:33316/limeEdu
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mail:
    host: smtp.gmail.com #
    port: 587 #
    username: 'bsbglobaldev'
    password: 'emmjckjbutkslalt' #
    properties:
      mail:
        smtp:
          auth: true #
          timeout: 5000 #
          starttls:
            enable: true #
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: C:\limeEdu\temp

server:
  port: 8000

logging:
  config: classpath:log4j2.xml
  level:
    com: info
    jdbc:
      resultsettable: info

ftp:
  host: 122.38.167.84
  port: 30321
  id: limeEdu
  password: limeEdu1!
  rootDir: /home/limeEdu/FTP
  serverType: ubuntu

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher